### ISSUE TITLE
Support for slot value matching

### ISSUE THREAD

**Issue by alopix** [BrianMacIntosh/alexa-skill-test-framework#23]
With a recent update, slots now support more than just a value but a match to a category, called resolutions.
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-standard-request-types-reference#intentrequest

Would be nice to specify these parameters in the IntentRequest builder as well.

**Comment by hoegertn** [comment]
this was added with the release this morning.

If there is something missing please reopen this issue.
