### ISSUE TITLE
TypeError: alexaTest.setDynamoDBTable is not a function

### ISSUE THREAD

**Issue by pdkn** [BrianMacIntosh/alexa-skill-test-framework#24]
'npm install alexa-skill-test-framework --save-dev' point to this branch:
https://github.com/BrianMacIntosh/alexa-skill-test-framework/blob/v1.1.1/index.js

Which doesn't contain the latest methods on master branch. Wonder if you can bump the version? Thxs

**Comment by hoegertn** [comment]
I plan to add the AudioPlayer tests today and cut a release then.
Is this ok?
