### ISSUE TITLE
Tests doesn't seem to terminate

### ISSUE THREAD

**Issue by jhnferraris** [BrianMacIntosh/alexa-skill-test-framework#29]
I am a noob in coding Alexa skills and I bump into your test framework. Cool tool btw.

I have a problem here when I try to run my tests. When I execute `npm test` it doesn't terminate

![screenshot from 2017-11-17 17-44-28](https://user-images.githubusercontent.com/3207153/32940913-01b349e2-cbbf-11e7-9241-94d6dc78cdf5.png)

I just followed the code in one of your examples as an experiment but I still have the same behavior.

```
const alexaTest = require('alexa-skill-test-framework');

alexaTest.initialize(
	require('../index.js'),
	"skill-id",
  'user-id');

describe("Alexa skill using Staging configuration", function() {
  describe("LaunchRequest", function() {
    alexaTest.test([
      {
        request: alexaTest.getLaunchRequest(),
        says: "Welcome!", repromptsNothing: true, shouldEndSession: true
      }
    ]);
  });
  describe("CountIntent", function() {
    const slot = {'companyMetadata': 'employees', 'siteName': 'fort'};
		const requestWithSlot = alexaTest.getIntentRequest('CountIntent', slot);

		alexaTest.test([
			{
				request: requestWithSlot,
				says: "fort has 61 employees", shouldEndSession: true, repromptsNothing: true
			}
		]);
  });
});
```

My node version is v9.0.0

package.json is

  "dependencies": {
    "alexa-sdk": "^1.0.12",
    "dotenv": "^4.0.0",
    "pg": "^7.4.0"
  },
  "devDependencies": {
    "alexa-skill-test-framework": "^1.1.2",
    "chai": "^4.1.2",
    "mocha": "^4.0.1"
  }

Appreciate the help.

**Comment by hoegertn** [comment]
Can you post (parts of) the code? Maybe disable all test and reenable them one by one to find the one that does not terminate.

**Comment by jhnferraris** [comment]
@hoegertn Apologies. I updated my post

**Comment by jhnferraris** [comment]
@hoegertn I tried running only the "LaunchIntent" test, still experience the same behavior.

My node version is v9.0.0

package.json is

```
  "dependencies": {
    "alexa-sdk": "^1.0.12",
    "dotenv": "^4.0.0",
    "pg": "^7.4.0"
  },
  "devDependencies": {
    "alexa-skill-test-framework": "^1.1.2",
    "chai": "^4.1.2",
    "mocha": "^4.0.1"
  }
```

**Comment by jhnferraris** [comment]
@hoegertn I disabled everything and left the `initialize` code. That was where the "stuck" happened

**Comment by jhnferraris** [comment]
@hoegertn Ah yes. I did not close it since the lambda function won't be able to connect to it again when I tried to asked Alexa to connect to the db again.

**Comment by hoegertn** [comment]
You can try to set `context.callbackWaitsForEmptyEventLoop = false;` in your handler function.

**Comment by jhnferraris** [comment]
@hoegertn Before execution? What does it do if you don't mind me asking?

**Comment by hoegertn** [comment]
As the first line in your handler function.
It tells Lambda to not block until all things on the event loop are gone.

I am not sure if it helps with your test problem, but it will cause trouble on AWS Lambda if not set.

**Comment by jhnferraris** [comment]
@hoegertn I tried it and it is still stuck. hmm

 So the issue here is because of the postgres Client not getting closed after the tests are finished.

**Comment by hoegertn** [comment]
@jhnferraris did you solve this issue? Can we close this one or is it still needed?
